CREATE TABLE [dbo].[Cabinet]
(
	[ID] INT NOT NULL PRIMARY KEY, 
    [RAISON_SOCIALE] VARCHAR(MAX) NOT NULL, 
    [SIRET] INT NULL, 
    [ADRESSE] VARCHAR(MAX) NULL, 
    [CODE_POSTAL] VARCHAR(10) NULL, 
    [VILLE] VARCHAR(200) NULL, 
    [TELEPHONE] VARCHAR(30) NULL, 
    [COMMENTAIRE] VARCHAR(MAX) NULL
)
