CREATE TABLE [dbo].[Collaborateur]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [ID_CABINET] INT NOT NULL, 
    [ROLE] VARCHAR(50) NOT NULL, 
    [TITRE] VARCHAR(50) NOT NULL, 
    [NOM] VARCHAR(200) NOT NULL, 
    [PRENOM] VARCHAR(200) NOT NULL, 
    [ADRESSE] VARCHAR(MAX) NULL, 
    [CODE_POSTAL] VARCHAR(10) NULL, 
    [VILLE] VARCHAR(200) NULL, 
    [TELEPHONE] VARCHAR(30) NULL, 
    [EMAIL] VARCHAR(200) NULL, 
    [DATE_CONNAISSANCE] DATE NULL, 
    [COMMENTAIRE] VARCHAR(MAX) NULL, 
    CONSTRAINT [FK_Collaborateur_ToCabinet] FOREIGN KEY (ID_CABINET) REFERENCES [Cabinet](ID) 
)
