//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionClient.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cabinet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cabinet()
        {
            this.Collaborateur = new HashSet<Collaborateur>();
        }
    
        public int ID { get; set; }
        public string RAISON_SOCIALE { get; set; }
        public Nullable<int> SIRET { get; set; }
        public string ADRESSE { get; set; }
        public string CODE_POSTAL { get; set; }
        public string VILLE { get; set; }
        public string TELEPHONE { get; set; }
        public string COMMENTAIRE { get; set; }
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collaborateur> Collaborateur { get; set; }
    }
}
