//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionClient.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaborateur
    {
        public int ID { get; set; }
        public int ID_CABINET { get; set; }
        public string ROLE { get; set; }
        public string TITRE { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string ADRESSE { get; set; }
        public string CODE_POSTAL { get; set; }
        public string VILLE { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DATE_CONNAISSANCE { get; set; }
        public string COMMENTAIRE { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
    }
}
