//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionClient.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaborateur
    {
        public int ID { get; set; }
        public int ID_CABINET { get; set; }
        public string ROLE { get; set; }
        public string TITRE { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string ADRESSE { get; set; }
        public string CODE_POSTAL { get; set; }
        public string VILLE { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DATE_CONNAISSANCE { get; set; }
        public string COMMENTAIRE { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
    }
}
